export { getComponentName } from "./getComponentName"
export { getIconName } from "./getComponentName"
export { cleanKeywords } from "./cleanKeywords"
export { cleanFileName } from "./cleanFileName"
export { validateSvg } from "./validateSvg"
